docker run
  -d
  --name='homepage'
  --net='bridge'
  -e TZ="Europe/Oslo"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="London"
  -e HOST_CONTAINERNAME="homepage"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png'
  -p '3000:3000/tcp'
  -v '/mnt/user/appdata/homepage':'/app/config':'rw'
  -v '/var/run/docker.sock':'/var/run/docker.sock':'ro'
  --env-file /mnt/user/appdata/homepage/.env 'ghcr.io/gethomepage/homepage:latest'

a41ce32a1c54eb66679ff147cc5da26ba891dc68ac12db44f576a69ca8c35142